# Generated by Django 6.0.1 on 2026-03-12 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_recipe_author_recipe_created_on_recipe_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.
                                             models.deletion.CASCADE,
                                             related_name='image',
                                             to='ledger.recipe')),
            ],
        ),
    ]
