# Generated by Django 6.0.1 on 2026-03-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipeimagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeImageModel',
            new_name='RecipeImage',
        ),
    ]
